Authenticator.Web/Controllers/AdministrationController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Authenticator.Web.Data;
using Authenticator.Web.Models;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;

namespace Authenticator.Web.Controllers
{
    public class AdministrationController : Controller
    {
        private readonly RoleManager<IdentityRole> _roleManager;
        private readonly UserManager<IdentityUser> _userManager;
        public AdministrationController(RoleManager<IdentityRole> roleManager, UserManager<IdentityUser> userManager)
        {
            _roleManager = roleManager;
            _userManager = userManager;
        }

        [HttpGet]
        public IActionResult Index()
        {
            return View();
        }


        [HttpGet]
        public IActionResult CreateRole()
        {
            return View();
        }

        [HttpGet]
        public IActionResult AddUserToRole()
        {
            var model = new AddUserToRoleViewModel()
            {
                UserOptions = new SelectList(_userManager.Users?.Select(x => x.UserName).ToList()),
                RoleOptions = new SelectList(_roleManager.Roles?.Select(x => x.Name).ToList())
            };

            return View(model);
        }

        [HttpPost]
        public async Task<IActionResult> AddUserToRole(AddUserToRoleViewModel viewModel)
        {
            if (ModelState.IsValid)
            {
                if (viewModel.User != null)
                {
                    var user = await _userManager.FindByNameAsync(viewModel.User);
                    if (viewModel.Role != null)
                    {
                        var role = await _roleManager.FindByNameAsync(viewModel.Role);
                        var result = await _userManager.AddToRoleAsync(user, role.Name);
                        if (result.Succeeded)
                        {
                            ViewData["Result"] = "User successfully added to the role.";
                            return View("AddUserToRoleResult");
                        }
                        else
                        {
                            foreach (var error in result.Errors)
                            {
                                ViewData["Result"] = error.Description;
                            }
                        }
                    }

                }                         
            }
            return View("AddUserToRoleResult");
        }

        [HttpPost]
        public async Task<IActionResult> CreateRole(CreateRoleViewModel createRoleViewModel)
        {
            if (ModelState.IsValid)
            {
                var role = new IdentityRole() { Name = createRoleViewModel.RoleName };
                var result = await _roleManager.CreateAsync(role);

                if (result.Succeeded)
                {
                    ViewData["Result"] = "Role has been created successfully.";
                    return View("CreateRoleResult");                    
                }

                foreach(IdentityError error in result.Errors)
                {
                    ModelState.AddModelError("", error.Description);
                }

            }

            ViewData["Result"] = "Role could not be created.";
            return View("CreateRoleResult");
        }

        [HttpGet]
        public async Task<IActionResult> ShowUsers()
        {
            var listOfUsers = new List<ShowUsersViewModel>();

            var users = _userManager.Users.ToList();
            var roles = _roleManager.Roles.ToList();
            var userInRole = false;
            var roleName = string.Empty;
            
            foreach (var user in users)
            {
                foreach (var role in roles)
                {
                    userInRole = await _userManager.IsInRoleAsync(user, role.Name);
                    if (userInRole)
                    {
                        roleName = role.Name;
                    }
                }
                listOfUsers.Add(new ShowUsersViewModel(){ Email  = user.Email, Role = roleName});
                roleName = null;
                userInRole = false;
            }

            return View(listOfUsers);
        }
    }
}

Authenticator.Web/Controllers/RegisteredInstancesController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using Authenticator.BL.Models;
using Authenticator.Web.Data;
using Microsoft.AspNetCore.Authorization;

namespace Authenticator.Web.Controllers
{
    [Authorize(Roles = "Admin")]
    public class RegisteredInstancesController : Controller
    {
        private readonly BusinessDbContext _context;

        public RegisteredInstancesController(BusinessDbContext context)
        {
            _context = context;
        }

        // GET: RegisteredInstances
        public async Task<IActionResult> Index()
        {
            var registeredInstances = _context.RegisteredInstances
                .Include(i => i.Instance)
                .ToListAsync();

            return View(await registeredInstances);
        }

        // GET: RegisteredInstances/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var registeredInstance = await _context.RegisteredInstances
                .Where(m => m.Id == id)
                .Include(i => i.Instance)
                .FirstOrDefaultAsync();

            if (registeredInstance == null)
            {
                return NotFound();
            }

            return View(registeredInstance);
        }

        // POST: RegisteredInstances/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var registeredInstance = await _context.RegisteredInstances.FindAsync(id);
            _context.RegisteredInstances.Remove(registeredInstance);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool RegisteredInstanceExists(int id)
        {
            return _context.RegisteredInstances.Any(e => e.Id == id);
        }
    }
}

Authenticator.Web/Controllers/RequestsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using Authenticator.BL.Models;
using Authenticator.Web.Data;
using Microsoft.AspNetCore.Authorization;

namespace Authenticator.Web.Controllers
{
    [Authorize(Roles = "Admin")]
    public class RequestsController : Controller
    {
        private readonly BusinessDbContext _context;

        public RequestsController(BusinessDbContext context)
        {
            _context = context;
        }

        // GET: Requests
        public IActionResult Index()
        {
            var instanceInfo = _context.InstanceInfoRequests
                    .Include(x => x.Instance)
                    .ToList();

            return View(instanceInfo);
        }

        // GET: Requests/Details/5
        public async Task<IActionResult> Approve(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var approvedItem = _context.InstanceInfoRequests
                .Where(m => m.RequestId == id)
                .Include(i => i.Instance)
                .FirstOrDefault();

            if (approvedItem == null)
            {
                return NotFound();
            }
            else
            {
                _context.RegisteredInstances.Add(
                    new RegisteredInstance() { 
                        Instance = approvedItem.Instance, 
                        RegistrationDate = DateTime.Now 
                    });

                _context.InstanceInfoRequests.Remove(approvedItem);
                await _context.SaveChangesAsync();
            }

            return View(approvedItem);
        }

        // GET: Requests/Delete/5
        public async Task<IActionResult> Decline(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var instanceInfoRequest = await _context.InstanceInfoRequests
                .Where(m => m.RequestId == id)
                .Include(i => i.Instance)
                .FirstOrDefaultAsync();

            if (instanceInfoRequest == null)
            {
                return NotFound();
            }

            return View(instanceInfoRequest);
        }

        // POST: Requests/Delete/5
        [HttpPost, ActionName("Decline")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var instanceInfoRequest = await _context.InstanceInfoRequests.FindAsync(id);
            _context.InstanceInfoRequests.Remove(instanceInfoRequest);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool InstanceInfoRequestExists(int id)
        {
            return _context.InstanceInfoRequests.Any(e => e.RequestId == id);
        }
    }
}

Authenticator.Web/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Authenticator.Web</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
</head>
<body style="background-color: #8C8C8C">
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light border-bottom box-shadow mb-3" style="background-color: #768692">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">
                    <img src="~/imgs/hydro.png" width="50" height="50"/>
                </a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex flex-sm-row-reverse">
                    <partial name="_LoginPartial" />
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-light" asp-controller="Administration" asp-action="Index">Administration</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-light" asp-controller="Requests" asp-action="Index">Requests</a>
                        </li> 
                        <li class="nav-item">
                            <a class="nav-link text-light" asp-controller="RegisteredInstances" asp-action="Index">Registered</a>
                        </li>     
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container text-light">
            &copy; 2019 - Authenticator
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @RenderSection("Scripts", required: false)
</body>
</html>